const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
const TELEGRAM_CHAT_ID = process.env.TELEGRAM_CHAT_ID;

const STATUS_MAP = {
  AutoCreated:{name:"Khách Mới",color:"#00a65a"},Chochuyenkhoan:{name:"CHỜ CHUYỂN KHOẢN",color:"#efb71a"},Chonhaphang:{name:"CHỜ NHẬP HÀNG",color:"#efb71a"},Choship:{name:"CHỜ SHIP",color:"#efb71a"},Chuachot:{name:"CHƯA CHỐT ĐƯỢC",color:"#77ab5c"},Chuaphatduoc:{name:"CHƯA PHÁT ĐƯỢC",color:"#efb71a"},Chuyenhang:{name:"CHUYỂN HÀNG",color:"#efb71a"},Chuyenhoan:{name:"CHUYỂN HOÀN",color:"#9e55a4"},Chuyenkhoanloi:{name:"CHUYỂN KHOẢN LỖI",color:"#d52609"},CODDathutien:{name:"COD-ĐÃ THU TIỀN",color:"#3dbcb3"},Giaohangcovande:{name:"GIAO HÀNG - CÓ VẤN ĐỀ",color:"#c50bd1"},Hengoilai:{name:"HẸN GỌI LẠI",color:"#efb71a"},Huyvandon:{name:"HUỶ VẬN ĐƠN",color:"#d52609"},"Huy DNX":{name:"HỦY ĐƠN",color:"#d52609"},Yeucauhuy:{name:"KHÁCH - YÊU CẦU HỦY",color:"#d52609"},Khonglayduochang:{name:"KHÔNG LẤY ĐƯỢC HÀNG",color:"#efb71a"},Khongnghemay:{name:"KHÔNG NGHE MÁY",color:"#d52609"},Lead:{name:"LEAD",color:"#00a65a"},Matdonhang:{name:"MẤT ĐƠN HÀNG",color:"#d52609"},Muatructiep:{name:"MUA TRỰC TIẾP",color:"#3dbcb3"},Daphathoanthanhcong:{name:"PHÁT HOÀN THÀNH CÔNG",color:"#9e55a4"},Daphatthanhcong:{name:"PHÁT THÀNH CÔNG",color:"#3dbcb3"},Saiso:{name:"SAI SỐ",color:"#efb71a"},Shipnoithanh:{name:"SHIP NỘI THÀNH",color:"#efb71a"},Thanhcong:{name:"THÀNH CÔNG",color:"#243ae0"},Tratienchonguoigui:{name:"TRẢ TIỀN NGƯỜI GỬI",color:"#3dbcb3"},Trungdon:{name:"TRÙNG ĐƠN",color:"#d52609"},Tuchoinhan:{name:"TỪ CHỐI NHẬN",color:"#9e55a4"},Dachot:{name:"ĐÃ CHỐT",color:"#efb71a"},Sent:{name:"ĐÃ GỬI",color:"#efb71a"},Daguibuudien:{name:"ĐÃ GỬI BĐ",color:"#2e96f7"},Dain:{name:"ĐÃ IN",color:"#006633"},Dathutien:{name:"ĐÃ THU TIỀN",color:"#3dbcb3"},Deleted:{name:"ĐÃ XOÁ ĐƠN",color:"#d52609"},Dadoisoat:{name:"ĐÃ ĐỐI SOÁT",color:"#044284"},Dadoisoatmotphan:{name:"ĐÃ ĐỐI SOÁT - MỘT PHẦN",color:"#8e44ad"},Dadonggoi:{name:"ĐÃ ĐÓNG GÓI",color:"#452b87"},Dathangtruoc:{name:"ĐẶT HÀNG TRƯỚC",color:"#009688"},Approved:{name:"ĐỀ NGHỊ XUẤT",color:"#efb71a"},Dienthoaiban:{name:"ĐIỆN THOẠI BẬN",color:"#efb71a"},Donhoatoc:{name:"ĐƠN HỎA TỐC ⚡",color:"#eb6b43"}
};

const STATUS_ICON = {
  AutoCreated:"",Chochuyenkhoan:"💳",Chonhaphang:"📥",Choship:"🚚",Chuachot:"🟡",Chuaphatduoc:"⚠️",Chuyenhang:"🔄",Chuyenhoan:"↩️",Chuyenkhoanloi:"❌",CODDathutien:"💰",Giaohangcovande:"🚨",Hengoilai:"📞",Huyvandon:"🗑️","Huy DNX":"❌",Yeucauhuy:"🙅",Khonglayduochang:"📦",Khongnghemay:"📵",Lead:"⭐",Matdonhang:"🔍",Muatructiep:"🤝",Daphathoanthanhcong:"✅",Daphatthanhcong:"✅",Saiso:"⚠️",Shipnoithanh:"🛵",Thanhcong:"✅",Tratienchonguoigui:"💸",Trungdon:"🔁",Tuchoinhan:"🚫",Dachot:"👍",Sent:"📤",Daguibuudien:"📮",Dain:"🖨️",Dathutien:"💵",Deleted:"🗑️",Dadoisoat:"🔎",Dadoisoatmotphan:"◐",Dadonggoi:"📦",Dathangtruoc:"📅",Approved:"📋",Dienthoaiban:"📵",Donhoatoc:"⚡"
};

const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
const productsOf=v=>Array.isArray(v)?v:(typeof v==="string"?(()=>{try{const x=JSON.parse(v);return Array.isArray(x)?x:[]}catch{return[]}})():[]);
function fmtVND(v){return new Intl.NumberFormat("vi-VN").format(Number(v||0))+" đ"}
function time(v){if(!v)return"";const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return new Intl.DateTimeFormat("vi-VN",{timeZone:"Asia/Ho_Chi_Minh",day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).format(d)}
function caption(body,ps){const s=STATUS_MAP[body.invoice_status]||{name:String(body.invoice_status||"KHÔNG RÕ").toUpperCase()};const statusIcon=STATUS_ICON[body.invoice_status]||"";const shop=(body.order_source_name||body.ecom_username||body.channel||"Không rõ").replace(/^VN-\s*/i,"");const id=body.name||body.eoi_order_id||body.invoice_no||"";let x=`${statusIcon ? statusIcon+" " : ""}<b>${esc(s.name)}</b> * ${esc(shop)}\n`;for(const p of ps){const rawName=p.item_name||p.model_name||p.item_sku||"Không rõ sản phẩm";const productName=rawName.slice(0,26).trimEnd();x+=`📦 ${esc(productName)}\n`;const sku=p.model_name||p.model_sku||p.item_sku||"";const qty=Number(p.model_quantity_purchased||p.active_qty||1);x+=`🔖 SKU: ${esc(sku||"-")} * ${qty}\n`;}if(!ps.length)x+="📦 Không có dữ liệu sản phẩm\n";if(body.ecom_doanhso!=null)x+=`💰 Doanh thu: ${fmtVND(body.ecom_doanhso)}\n`;x+=`\n🧾 Mã đơn: ${esc(id)}\n`;const deposit=Number(body.tiendatcoc||0);x+=`Khách Thanh Toán: ${deposit===0?"COD":fmtVND(deposit)}\n\n👤 Người nhận: ${esc(body.receiver||"")}`;if(body.phone_number)x+=` - ${esc(body.phone_number)}`;x+="\n";if(body.address)x+=`Địa chỉ: ${esc(body.address)}\n`;x+=time(body.created_at||body.updated_at||body.invoice_date);return x.trim()}
async function tg(method,payload){const r=await fetch(`https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const t=await r.text();if(!r.ok)throw new Error(`Telegram ${r.status}: ${t}`);return JSON.parse(t)}
async function send(body){const ps=productsOf(body.products);const text=caption(body,ps);const photo=ps[0]?.image_info?.image_url;if(photo&&text.length<=1024)await tg("sendPhoto",{chat_id:TELEGRAM_CHAT_ID,photo,caption:text,parse_mode:"HTML"});else await tg("sendMessage",{chat_id:TELEGRAM_CHAT_ID,text:text.slice(0,4096),parse_mode:"HTML",disable_web_page_preview:true})}
export default async function handler(req,res){if(req.method==="GET")return res.status(200).json({ok:true,service:"AbitStore Webhook -> Telegram",version:"37.0-payment-info-v2"});if(req.method!=="POST")return res.status(405).json({ok:false,error:"Method Not Allowed"});try{await send(req.body??{});return res.status(200).json({ok:true,telegram:"sent",pushes:1})}catch(e){console.error(e);return res.status(500).json({ok:false,error:e.message})}}