const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
const TELEGRAM_CHAT_ID = process.env.TELEGRAM_CHAT_ID;

const STATUS_MAP = {
  AutoCreated:{name:"KHÁCH MỚI",color:"#00a65a"},Chochuyenkhoan:{name:"CHỜ CHUYỂN KHOẢN",color:"#efb71a"},Chonhaphang:{name:"CHỜ NHẬP HÀNG",color:"#efb71a"},Choship:{name:"CHỜ SHIP",color:"#efb71a"},Chuachot:{name:"CHƯA CHỐT ĐƯỢC",color:"#77ab5c"},Chuaphatduoc:{name:"CHƯA PHÁT ĐƯỢC",color:"#efb71a"},Chuyenhang:{name:"CHUYỂN HÀNG",color:"#efb71a"},Chuyenhoan:{name:"CHUYỂN HOÀN",color:"#9e55a4"},Chuyenkhoanloi:{name:"CHUYỂN KHOẢN LỖI",color:"#d52609"},CODDathutien:{name:"COD-ĐÃ THU TIỀN",color:"#3dbcb3"},Giaohangcovande:{name:"GIAO HÀNG - CÓ VẤN ĐỀ",color:"#c50bd1"},Hengoilai:{name:"HẸN GỌI LẠI",color:"#efb71a"},Huyvandon:{name:"HUỶ VẬN ĐƠN",color:"#d52609"},"Huy DNX":{name:"HỦY ĐƠN",color:"#d52609"},Yeucauhuy:{name:"KHÁCH - YÊU CẦU HỦY",color:"#d52609"},Khonglayduochang:{name:"KHÔNG LẤY ĐƯỢC HÀNG",color:"#efb71a"},Khongnghemay:{name:"KHÔNG NGHE MÁY",color:"#d52609"},Lead:{name:"LEAD",color:"#00a65a"},Matdonhang:{name:"MẤT ĐƠN HÀNG",color:"#d52609"},Muatructiep:{name:"MUA TRỰC TIẾP",color:"#3dbcb3"},Daphathoanthanhcong:{name:"PHÁT HOÀN THÀNH CÔNG",color:"#9e55a4"},Daphatthanhcong:{name:"PHÁT THÀNH CÔNG",color:"#3dbcb3"},Saiso:{name:"SAI SỐ",color:"#efb71a"},Shipnoithanh:{name:"SHIP NỘI THÀNH",color:"#efb71a"},Thanhcong:{name:"THÀNH CÔNG",color:"#243ae0"},Tratienchonguoigui:{name:"TRẢ TIỀN NGƯỜI GỬI",color:"#3dbcb3"},Trungdon:{name:"TRÙNG ĐƠN",color:"#d52609"},Tuchoinhan:{name:"TỪ CHỐI NHẬN",color:"#9e55a4"},Dachot:{name:"ĐÃ CHỐT",color:"#efb71a"},Sent:{name:"ĐÃ GỬI",color:"#efb71a"},Daguibuudien:{name:"ĐÃ GỬI BĐ",color:"#2e96f7"},Dain:{name:"ĐÃ IN",color:"#006633"},Dathutien:{name:"ĐÃ THU TIỀN",color:"#3dbcb3"},Deleted:{name:"ĐÃ XOÁ ĐƠN",color:"#d52609"},Dadoisoat:{name:"ĐÃ ĐỐI SOÁT",color:"#044284"},Dadoisoatmotphan:{name:"ĐÃ ĐỐI SOÁT - MỘT PHẦN",color:"#8e44ad"},Dadonggoi:{name:"ĐÃ ĐÓNG GÓI",color:"#452b87"},Dathangtruoc:{name:"ĐẶT HÀNG TRƯỚC",color:"#009688"},Approved:{name:"ĐỀ NGHỊ XUẤT",color:"#efb71a"},Dienthoaiban:{name:"ĐIỆN THOẠI BẬN",color:"#efb71a"},Donhoatoc:{name:"ĐƠN HỎA TỐC ⚡",color:"#eb6b43"}
};

const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
const productsOf=v=>Array.isArray(v)?v:(typeof v==="string"?(()=>{try{const x=JSON.parse(v);return Array.isArray(x)?x:[]}catch{return[]}})():[]);
function icon(hex){const h=String(hex||"").toLowerCase();if(h==="#d52609"||h==="#c50bd1")return"🔴";if(h==="#efb71a"||h==="#eb6b43")return"🟠";if(h==="#00a65a"||h==="#77ab5c"||h==="#006633")return"🟢";if(h==="#3dbcb3"||h==="#2e96f7"||h==="#243ae0"||h==="#044284")return"🔵";if(h==="#9e55a4"||h==="#8e44ad"||h==="#452b87")return"🟣";return"⚫"}
function fmtVND(v){return new Intl.NumberFormat("vi-VN").format(Number(v||0))+" đ"}
function time(v){if(!v)return"";const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return new Intl.DateTimeFormat("vi-VN",{timeZone:"Asia/Ho_Chi_Minh",day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).format(d)}
function caption(body,ps){const s=STATUS_MAP[body.invoice_status]||{name:String(body.invoice_status||"KHÔNG RÕ").toUpperCase(),color:"#737373"};const shop=body.order_source_name||body.ecom_username||body.channel||"Không rõ";const id=body.name||body.eoi_order_id||body.invoice_no||"";let x=`${icon(s.color)} <b>${esc(s.name)}</b>\n`;for(const p of ps){const rawName=p.item_name||p.model_name||p.item_sku||"Không rõ sản phẩm";const productName=rawName.slice(0,26).trimEnd();x+=`📦 ${esc(productName)}\n`;const sku=p.model_name||p.model_sku||p.item_sku||"";const qty=Number(p.model_quantity_purchased||p.active_qty||1);x+=`SKU: ${esc(sku||"-")} * ${qty}\n`;}if(!ps.length)x+="📦 Không có dữ liệu sản phẩm\n";if(body.ecom_doanhso!=null)x+=`Doanh thu: ${fmtVND(body.ecom_doanhso)}`;x+=`\n\n🏪 Shop: ${esc(shop)}\nMã đơn: ${esc(id)}\n\n👤 Người nhận: ${esc(body.receiver||"")}`;if(body.phone_number)x+=` - ${esc(body.phone_number)}`;x+="\n";if(body.address)x+=`Địa chỉ: ${esc(body.address)}\n`;x+=time(body.created_at||body.updated_at||body.invoice_date);return x.trim()}
async function tg(method,payload){const r=await fetch(`https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const t=await r.text();if(!r.ok)throw new Error(`Telegram ${r.status}: ${t}`);return JSON.parse(t)}
async function sendDebugJson(body,replyToMessageId){const json=JSON.stringify(body,null,2);const name=`abitstore-webhook-${body.name||body.eoi_order_id||Date.now()}.json`;const fd=new FormData();fd.append("chat_id",TELEGRAM_CHAT_ID);fd.append("document",new Blob([json],{type:"application/json"}),name);fd.append("caption","DEBUG JSON - AbitStore Webhook");if(replyToMessageId)fd.append("reply_parameters",JSON.stringify({message_id:replyToMessageId}));const r=await fetch(`https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument`,{method:"POST",body:fd});const t=await r.text();if(!r.ok)throw new Error(`Telegram sendDocument ${r.status}: ${t}`);return JSON.parse(t)}
async function send(body){const ps=productsOf(body.products);const text=caption(body,ps);const photo=ps[0]?.image_info?.image_url;let mainMessage;if(photo&&text.length<=1024)mainMessage=await tg("sendPhoto",{chat_id:TELEGRAM_CHAT_ID,photo,caption:text,parse_mode:"HTML"});else mainMessage=await tg("sendMessage",{chat_id:TELEGRAM_CHAT_ID,text:text.slice(0,4096),parse_mode:"HTML",disable_web_page_preview:true});await sendDebugJson(body,mainMessage?.result?.message_id)}
export default async function handler(req,res){if(req.method==="GET")return res.status(200).json({ok:true,service:"AbitStore Webhook -> Telegram",version:"22.0-debug-reply"});if(req.method!=="POST")return res.status(405).json({ok:false,error:"Method Not Allowed"});try{await send(req.body??{});return res.status(200).json({ok:true,telegram:"sent",order_pushes:1,debug_json:"sent_as_reply",total_telegram_messages:2})}catch(e){console.error(e);return res.status(500).json({ok:false,error:e.message})}}